name: Release
on:
  push: { tags: ['v*'] }
permissions: { contents: read }
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with: { node-version: 24 }
      - run: npm ci
      - run: npm run gen:grammar && npm run compile
      - name: Publish to VS Code Marketplace
        run: npx @vscode/vsce publish
        env: { VSCE_PAT: '${{ secrets.VSCE_PAT }}' }
      - name: Publish to Open VSX
        run: npx ovsx publish
        env: { OVSX_PAT: '${{ secrets.OVSX_PAT }}' }
